server:
  port: 8080

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**,/users/**,/organisations/**,/roles/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
